print("Name in a box")
print()
name = input("please enter your name: ")
print()
print( "~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print("|" + f"{name.upper()}" .ljust(25) + "|")
print("|" + f"{name.capitalize()}" .center(25) + "|")
print("|" + f"{name}" .rjust(25) + "|")
print("~~~~~~~~~~~~~~~~~~~~~~~~~~~")